### ISSUE TITLE
Invalid alert data. Cannot save dashboard

### ISSUE THREAD

**Issue by jangrewe** [bergquist/dashboards#8]
I can't save the node-exporter dashboard because the alerts for each graph seem to use invalid queries:
```
 Template variables are not supported in alert queries
```

**Comment by bergquist** [comment]
Thanks for posting this! Super sorry for the slow response :( seems it go lost in github notifications.

**Comment by thomasbinny1989** [comment]
@bergquist  So  my teammate and me, we  came past the same problem and have removed the alert bit of the code from the template. Do we have some kind of fix to automatically create alerts since and alert can not be created without having dashboards. Please provide us a latest status, or should we still create the dashboards and manually create the alarms.
